# Run terraform actions on your behalf
steps:
  - id: berglas
    name: us-docker.pkg.dev/berglas/berglas/berglas:latest
    env:
      - CREDENTIALS=berglas://${_BUCKET_ID}/gcp-credentials?destination=/secrets/gcp-credentials
    args: [ "exec", "--", "/bin/sh" ]
    volumes:
      - name: secrets
        path: /secrets

  - name: gcr.io/${_PROJECT}/gcloud-terraform:latest
    id: 'terraform_deploy'
    entrypoint: /bin/bash
    args:
      - -exc
      - |
        cd provision
        mkdir credentials
        cp /secrets/gcp-credentials credentials/account.json
        terraform init
        terraform $_ACTION -var-file=terraform.tfvars
    volumes:
      - name: secrets
        path: /secrets
  
  - name: gcr.io/cloud-builders/kubectl
    id: Set namespaces
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        cd provision
        kubectl create namespace nfs
        kubectl -n nfs apply -f nfs/nfs-server.yaml
        kubectl create namespace storage
        kubectl create namespace airflow
        $(kubectl -n nfs get service/nfs-server -o jsonpath="{.spec.clusterIP}") > /workspace/nfs_server.txt
    env:
      - CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}
      - CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
  
  - name: gcr.io/${_PROJECT}/helm
    id: Install charts
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        cd kubernetes
        helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
        helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner --namespace storage --set nfs.server=$(cat /workspace/nfs_server.txt) --set nfs.path=/
        helm repo add apache-airflow https://airflow.apache.org
        helm install airflow -f airflow-values.yaml apache-airflow/airflow --namespace airflow


substitutions:
  _ACTION: "apply -auto-approve"
  _BUCKET_ID: "airflow-cloud_keys"
  _ENV: "dev"
  _PROJECT: "airflow-cloud"
  _CLOUDSDK_COMPUTE_ZONE: "us-central1"
  _CLOUDSDK_CONTAINER_CLUSTER: "airflow-gke-data-bootcamp"

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s