# Run terraform actions on your behalf
steps:
  - id: berglas
    name: us-docker.pkg.dev/berglas/berglas/berglas:latest
    env:
      - CREDENTIALS=berglas://${_BUCKET_ID}/gcp-credentials?destination=/secrets/gcp-credentials
    args: [ "exec", "--", "/bin/sh" ]
    volumes:
      - name: secrets
        path: /secrets

  - name: gcr.io/${_PROJECT}/gcloud-terraform:latest
    id: 'terraform_deploy'
    entrypoint: /bin/bash
    args:
      - -exc
      - |
        cd provision
        mkdir credentials
        cp /secrets/gcp-credentials credentials/account.json
        terraform init
        terraform $_ACTION -var-file=terraform.tfvars
    volumes:
      - name: secrets
        path: /secrets

substitutions:
  _ACTION: "apply -auto-approve"
  _BUCKET_ID: "airflow-cloud_keys"
  _ENV: "dev"
  _PROJECT: "airflow-cloud"

options:
  substitution_option: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s